package com.moovers.monitor.util

object TestTags {

    const val SEARCH_SECTION = "SEARCH_SECTION"
    const val BOTTOM_TAB_SECTION = "BOTTOM_TAB_SECTION"
    const val NO_TEXT_SECTION = "NO_TEXT_SECTION"
    const val PROGRESS_BAR_SECTION = "PROGRESS_BAR_SECTION"
    const val CIRCLE_PROGRESS_BAR_SECTION = "CIRCLE_PROGRESS_BAR_SECTION"
    const val GOOGLE_MAP_SECTION = "GOOGLE_MAP_SECTION"
    const val BTN_ACTION = "BTN_ACTION"
}